// GENERATED by config/scripts/generate-orcad-wire-vectors.mjs — do not edit by hand.
export type OrcadWireVectors = {
  generatedBy: string
  formatVersion: 1
  keys: {
    serverPublicKeyB64: string
    serverSecretKeyB64: string
    clientPublicKeyB64: string
    clientSecretKeyB64: string
    sharedKeyB64: string
  }
  pairing: {
    offer: { v: 2; endpoint: string; deviceToken: string; publicKeyB64: string; scope: 'runtime' }
    url: string
    bareCode: string
  }
  handshake: {
    helloPlaintext: string
    readyPlaintext: string
    authPlaintext: string
    authenticatedPlaintext: string
    unauthorizedPlaintext: string
    badAuthPlaintext: string
  }
  sealed: {
    authenticated: string
    unauthorized: string
    badAuth: string
    rpcResponse: string
    keepalive: string
    truncated: string
    oversize: string
    nonBase64: string
  }
  rpc: { requestPlaintext: string; responsePlaintext: string; keepalivePlaintext: string }
}

export const ORCAD_WIRE_VECTORS: OrcadWireVectors = {
  "generatedBy": "config/scripts/generate-orcad-wire-vectors.mjs",
  "formatVersion": 1,
  "keys": {
    "serverPublicKeyB64": "MidkCbgSKMXEIbGTK7vtf/2VwC+9F9Nb3ev7EeAJT3c=",
    "serverSecretKeyB64": "41wCzh0R97EktQmtipLc3/+wt92nNKkO4VaMl+tTZHw=",
    "clientPublicKeyB64": "/HHQcOZDMeT9hCSPdPJHIBFz/2Zy0pj/PCcVZh+OyQE=",
    "clientSecretKeyB64": "NTS3nzowA71ISa/b94pKKLvE6S2q/AdivFMO5aZJ2GA=",
    "sharedKeyB64": "vL4EyAIJUX6uxfGxdzQ14rWORMG/7bfiMe5qdTaQZnQ="
  },
  "pairing": {
    "offer": {
      "v": 2,
      "endpoint": "ws://127.0.0.1:5170",
      "deviceToken": "orcad-wire-vector-device-token",
      "publicKeyB64": "MidkCbgSKMXEIbGTK7vtf/2VwC+9F9Nb3ev7EeAJT3c=",
      "scope": "runtime"
    },
    "url": "orca://pair?code=eyJ2IjoyLCJlbmRwb2ludCI6IndzOi8vMTI3LjAuMC4xOjUxNzAiLCJkZXZpY2VUb2tlbiI6Im9yY2FkLXdpcmUtdmVjdG9yLWRldmljZS10b2tlbiIsInB1YmxpY0tleUI2NCI6Ik1pZGtDYmdTS01YRUliR1RLN3Z0Zi8yVndDKzlGOU5iM2V2N0VlQUpUM2M9Iiwic2NvcGUiOiJydW50aW1lIn0",
    "bareCode": "eyJ2IjoyLCJlbmRwb2ludCI6IndzOi8vMTI3LjAuMC4xOjUxNzAiLCJkZXZpY2VUb2tlbiI6Im9yY2FkLXdpcmUtdmVjdG9yLWRldmljZS10b2tlbiIsInB1YmxpY0tleUI2NCI6Ik1pZGtDYmdTS01YRUliR1RLN3Z0Zi8yVndDKzlGOU5iM2V2N0VlQUpUM2M9Iiwic2NvcGUiOiJydW50aW1lIn0"
  },
  "handshake": {
    "helloPlaintext": "{\"type\":\"e2ee_hello\",\"publicKeyB64\":\"/HHQcOZDMeT9hCSPdPJHIBFz/2Zy0pj/PCcVZh+OyQE=\"}",
    "readyPlaintext": "{\"type\":\"e2ee_ready\"}",
    "authPlaintext": "{\"type\":\"e2ee_auth\",\"deviceToken\":\"orcad-wire-vector-device-token\",\"clientCapabilities\":[]}",
    "authenticatedPlaintext": "{\"type\":\"e2ee_authenticated\"}",
    "unauthorizedPlaintext": "{\"type\":\"e2ee_error\",\"error\":{\"code\":\"unauthorized\"}}",
    "badAuthPlaintext": "{\"type\":\"e2ee_error\",\"error\":{\"code\":\"bad_auth\"}}"
  },
  "sealed": {
    "authenticated": "GSbxu4wt8HwK8GBmmu06N2dAtWYP24b7A9Z/TxM14UGbIAC8C1eE5gXhll4JjX9iFwjxAmukp6yyIv2i+i36PLprqG+q",
    "unauthorized": "0xuGRzREbmrFDbPg6/85azoDo9PEOJy0ivpAQIodDlH0rgz9NOyt9wUHGMVIFJyOGViU4R8dCTlweRcAun/1JY8YG14crtlKn0Yb25PtbxK2pA8TNoCi1XsN3mZb",
    "badAuth": "Kw7FKeSS14GkNq8kmGUCEKtY+XFJRAYeG9nKf0K0oHOCNdnWFerV5QA+8T5Xp0HMche0tslcyD3hssF8ddoLC4HMsFQTv5NmsOhagrvynmITNbcMwmVdv8E=",
    "rpcResponse": "sSX2ovYECyovYWJGL02EOoEnlmkk0sQlfrnl8T+5oX30YVe7I8KBOL5YG/jNuLdtfeR0n2/V99R7in75+6QBMuzUE4SYkCAWvi4YU7eY4UtQ4Coo72+TLS0fWugqs89mOaT43qLF6EWXL0JlAk2B+3j3mmHU6FVWEUxY1gvfgKIHUxidHTR0I45xTARrfQ==",
    "keepalive": "SoMLcCJcrVzQ8rbSCFQBwrqZD6QCbzAcZJljIhmYfIq2A6So9x67lRr8NZxHwnlC0bZC3KIzrHxVQ1M=",
    "truncated": "GSbxu4wt8HwK8A==",
    "oversize": 'A'.repeat(5592464),
    "nonBase64": "GSbxu4!!!HwK8GBmmu06N2dAtWYP24b7A9Z/TxM14UGbIAC8C1eE5gXhll4JjX9iFwjxAmukp6yyIv2i+i36PLprqG+q"
  },
  "rpc": {
    "requestPlaintext": "{\"id\":\"vector-request-1\",\"deviceToken\":\"orcad-wire-vector-device-token\",\"method\":\"worktree.list\"}",
    "responsePlaintext": "{\"id\":\"vector-request-1\",\"ok\":true,\"result\":{\"worktrees\":[]},\"_meta\":{\"runtimeId\":\"vector-runtime-1\"}}",
    "keepalivePlaintext": "{\"_keepalive\":true}"
  }
}
